# Site settings
title: "Sunil Murthy"
tagline: "Software Developer & Tech Enthusiast"
description: "Personal website and portfolio showcasing projects, skills, and professional experience."
url: "https://sunilmurthy.github.io"
baseurl: ""

# Author information
author:
  name: "Sunil Murthy"
  email: "sunil.murthy@example.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Hyde theme settings
version: 2.1.0

# Sidebar links
github:
  repo: https://github.com/sunhick

# Navigation
nav:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "Portfolio"
    url: "/portfolio/"
  - name: "Skills"
    url: "/skills/"
  - name: "Contact"
    url: "/contact/"

# Social links
social:
  github: "sunhick"
  linkedin: "sunhick"
  email: "sunhick@gmail.com"

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Defaults
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
